### ISSUE TITLE
请问各个版本的yolo的预训练模型在哪

### ISSUE THREAD

**Issue by songjiahao-wq** [iscyy/ultralyticsPro#1]

**Comment by iscyy** [comment]
not yet

**Comment by iscyy** [comment]
This Repo will soon provide pre-trained weights for YOLOv3, YOLOv4, YOLOv5, YOLOv7, YOLOR, etc. and other network models.

**Comment by iscyy** [comment]
https://github.com/iscyy/yoloair/releases
