### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type __int64

### ISSUE THREAD

**Issue by 17076372880** [iscyy/ultralyticsPro#10]
佬你好，这个错误咋回事捏？

**Comment by iscyy** [comment]
hi, Can you describe it more clearly?

**Comment by XayOn** [comment]
Not sure about @17076372880 , but I can: https://github.com/ultralytics/yolov5/issues/8405

This happens for torch > 1.10, wich is required for python3.10
