### ISSUE TITLE
MLP family

### ISSUE THREAD

**Issue by daiyuanm** [iscyy/ultralyticsPro#100]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Thanks for your work!

I noticed that there exists a file named  [yolov5s_WaveLAN.yaml](https://github.com/iscyy/yoloair/blob/main/configs/mlp/yolov5s_WaveLAN.yaml), but there is no corresponding WaveLAN block in common.py and yolo.py. Did the author forget to add it?

And I wonder if wavelan is from [An Image Patch is a Wave: Phase-Aware Vision MLP](https://arxiv.org/abs/2111.12294)

**Comment by iscyy** [comment]
yeah
