### ISSUE TITLE
is there any guidliance to do trainig & use custom functions?

### ISSUE THREAD

**Issue by akashAD98** [iscyy/ultralyticsPro#103]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

i want to implement different Backbone,data augmentation,loss, and neck in yolov7 repo, so what things should I need to change? is there any specific format ?

**Comment by iscyy** [comment]
You can refer to the files under configs/yolov7-Improved and configs/yolov7-transformer-Improved, and other files under congigs

**Comment by akashAD98** [comment]
@iscyy thanks but how can i change this parameters such as   loss, IoU, NMS , should I need to update it in .yaml file or is there any arguments for this?
