### ISSUE TITLE
为什么YOLOX-s官网上的算力是26.8GFLOPs，而通过YOLOAir训练YOLOX-s却是22GFLOPs，哪些地方不一样？

### ISSUE THREAD

**Issue by lixiangMindSpore** [iscyy/ultralyticsPro#105]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

为什么YOLOX-s官网上的算力是26.8GFLOPs，而通过YOLOAir训练YOLOX-s却是22GFLOPs，哪些地方不一样？
![Uploading 3e3feebbc637f7fc36b141328c38bb1.jpg…]()

python -m torch.distributed.run --nproc_per_node 3 train.py --data coco.yaml --weight '' --cfg configs/yolox/yolox-s.yaml --img 640  --noautoanchor --device 0,1,2 --batch-size 192 --otaloss yolox --epochs 300

### Additional

为什么YOLOX-s官网上的算力是26.8GFLOPs，而通过YOLOAir训练YOLOX-s却是22GFLOPs，哪些地方不一样？
![3e3feebbc637f7fc36b141328c38bb1](https://user-images.githubusercontent.com/78945582/192183854-35be68e8-40a5-45a7-81d8-d5d6a499cfd6.jpg)

python -m torch.distributed.run --nproc_per_node 3 train.py --data coco.yaml --weight '' --cfg configs/yolox/yolox-s.yaml --img 640  --noautoanchor --device 0,1,2 --batch-size 192 --otaloss yolox --epochs 300

**Comment by Muyangg** [comment]
你跑通了YOLOX没？能否加个联系方式讨论一下

**Comment by lixiangMindSpore** [comment]
> 你跑通了YOLOX没？能否加个联系方式讨论一下

我跑通了，hyperxiangye
