### ISSUE TITLE
CNeB not ELAN in yolov7 with MobileOne backbone?

### ISSUE THREAD

**Issue by usera1** [iscyy/ultralyticsPro#108]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

This is really an excellent work! Thanks for your hard workinig. But a little confused about yolov7 with MobileOne backbone:
In the yolov7-MobileOne.yaml file, there are CNeB and C2C3 modules instead of ELAN module in original yolov7?
![CNeB](https://user-images.githubusercontent.com/52943543/192739955-cf59f088-920b-4462-afcb-c41699b790fd.png)
![ELAN](https://user-images.githubusercontent.com/52943543/192739967-c208560f-3e5d-41d5-8e3d-d7a5942d650b.png)

**Comment by iscyy** [comment]
The original official yolov7 model is an ELAN structure, but in the improved yolov7 model provided here, the ELAN structure is replaced with a CNeB structure, that's all. You can choose to replace the ELAN structure with CNeB again, which is all possible

**Comment by usera1** [comment]
Got it, thanks!
