### ISSUE TITLE
训练YOLOX的超参也在hyp.scratch.p5.yaml吗？想修改数据增强方式

### ISSUE THREAD

**Issue by lixiangMindSpore** [iscyy/ultralyticsPro#110]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

训练YOLOX的超参也在YOLOX的超参也在hyp.scratch.p5.yaml吗？想修改数据增强方式

**Comment by iscyy** [comment]
Regarding this part, yolov5 has been reused for the time being, and will be updated later
