### ISSUE TITLE
Where is the Dynamic Head module ，Can you give me a hint

### ISSUE THREAD

**Issue by songjiahao-wq** [iscyy/ultralyticsPro#111]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Where is the Dynamic Head module ，Can you give me a hint

**Comment by iscyy** [comment]
There is no update for main at the moment, only the beta branch, and then the main branch will be updated
