### ISSUE TITLE
./configs/yolov5_exp/yolov5s_C3GC.yaml 请问这个C3GC是具体哪个网络来的？没有找到相关信息

### ISSUE THREAD

**Issue by LitChi-bit** [iscyy/ultralyticsPro#112]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

请问这个C3GC是GCNet还是什么东西，没有在网上检索到相关内容

**Comment by iscyy** [comment]
GCNet

**Comment by LitChi-bit** [comment]
好的，非常感谢
