### ISSUE TITLE
Can you show the values of the associated trained model on the validation set? such as precision, recall, loss?

### ISSUE THREAD

**Issue by Jacky-Android** [iscyy/ultralyticsPro#113]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/55181594/194295388-92682c27-10d9-44cb-9113-6d02e6975920.png)
Ending an epoch with no indices displayed.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by iscyy** [comment]
default is ok
