### ISSUE TITLE
The following problems were encountered with the installation:No matching distribution found for cvms

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#117]
![image](https://user-images.githubusercontent.com/105439021/195023586-56640004-bdc7-43f3-8a81-f2589f5b77d5.png)
No matching distribution found for cvms

**Comment by iscyy** [comment]
What is your environment? Local Linux, Win, Mac, or Linux for cloud GPUs? I have tested Colab, local linux, Win, and Mac are all normal, but the Linux provided by some cloud GPUs cannot be installed

**Comment by ghost** [comment]
Cloud GPU provided by linux.Just this cvms can't be installed

**Comment by iscyy** [comment]
This may be related to the Linux provided by cloud GPU,

**Comment by ghost** [comment]
> This may be related to the Linux provided by cloud GPU,

But I was also using this cloud gpu before，After a week interval, it doesn't work
