### ISSUE TITLE
请问关于./configs/yolov5_exp中yaml文件的一个困惑

### ISSUE THREAD

**Issue by LitChi-bit** [iscyy/ultralyticsPro#122]
你好，请问在./configs/yolov5_exp中，yolov5s_C3GC.yaml的backbone部分将C3替换为了C3GC，但是在yolov5s_C3GC_p6.yaml中，backbone没有对C3进行修改
这里不是很懂，谢谢

**Comment by LitChi-bit** [comment]
其中，我测试将yolov5s_C3GC_p6.yaml中的c3改为c3gc后，效果反而不如本来的，但是又比yolov5s_p6的效果好

**Comment by zmdcs** [comment]
请问你知道C3GC是什么网络吗？

**Comment by LitChi-bit** [comment]
是GC Net
