### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type __int64

### ISSUE THREAD

**Issue by zcswdt** [iscyy/ultralyticsPro#129]
How to correct this error? thank you

![image](https://user-images.githubusercontent.com/43515926/197380519-a551fd16-4128-484f-be55-d4931930298c.png)

**Comment by zcswdt** [comment]
How to correct this error? thank you

**Comment by HIT-Owen** [comment]
用main分支的代码，beta分支的loss.py里面有问题
