### ISSUE TITLE
ModuleNotFoundError: No module named 'timm'

### ISSUE THREAD

**Issue by Logan-lu** [iscyy/ultralyticsPro#13]
Following setup steps in README.md, when running training script (python train.py --data coco128.yaml --cfg configs/yolov5/yolov5s.yaml), met the following errors:

Downloading https://ultralytics.com/assets/Arial.ttf to /home/logan/.config/Ultralytics/Arial.ttf...
Traceback (most recent call last):
  File "/home/logan/dev/pyfarm/pytorch/yoloair/train.py", line 41, in <module>
    import val  # for end-of-epoch mAP
  File "/home/logan/dev/pyfarm/pytorch/yoloair/val.py", line 38, in <module>
    from models.common import DetectMultiBackend
  File "/home/logan/dev/pyfarm/pytorch/yoloair/models/common.py", line 35, in <module>
    from models.Models.muitlbackbone import conv_bn_hswish, MobileNetV3_InvertedResidual, DepthSepConv, \
  File "/home/logan/dev/pyfarm/pytorch/yoloair/models/Models/muitlbackbone.py", line 26, in <module>
    from models.Models.SwinTransformer import SwinTransformerLayer
  File "/home/logan/dev/pyfarm/pytorch/yoloair/models/Models/SwinTransformer.py", line 9, in <module>
    from timm.models.layers import DropPath, to_2tuple, trunc_normal_
ModuleNotFoundError: No module named 'timm'

Any help?

P.S. My env: Ubuntu22.04.1, python 3.10.4

**Comment by iscyy** [comment]
`pip install timm`

**Comment by iscyy** [comment]
you can use `pip install timm`

**Comment by zhongsir771** [comment]
pip is useful

**Comment by gaoabc** [comment]
I solved this problem by reconfiguring the runtime environment, but I encountered a new problem when using the train.py file: File "Fossil-ID-Multiview-Deep-Ensembles- main/train.py", line 39, in <module>
    from timm.scheduler import create_scheduler_v2, scheduler_kwargs
ImportError: cannot import name 'create_scheduler_v2' from 'timm.scheduler'. 
I think this may be a problem with the version of timm, what is the version of your timm?
