### ISSUE TITLE
about SwinTransformer+yolov5 training， PR and mAP is 0

### ISSUE THREAD

**Issue by emmobaby** [iscyy/ultralyticsPro#131]
I use the official swin transformer configuration file (yolov5_ swin_ transfomrer-V2.yaml) and training tutorial provided on the CSDN. During training, PR and other indicators are always 0 for each epoch verification. However, this problem will not occur if I change to the general yolov5 (yolov5m.yaml).

I have tried to change the version of python, and adopted python, 3.7/3.8/3.9, cuda=10.2, and pytorch=1.8/1.9/1.10. None of these methods works

It should be possible to eliminate the problem of data sets. After all, I can use the official yolov5 to train successfully

Then I also found a problem, that is, in the training process, there will be a train under run/train/exp_ batch0.jpg、train_ batch1.jpg、train_ Batch2.jpg, these image files can correctly display the detection results, so I wonder if there is a problem with the configuration file?

I follow https://blog.csdn.net/qq_38668236/article/details/126735107

And my training command is: python train py --cfg yolov5_ swin_ transfomrer-V2.yaml --weight '' --data data/VisDrone. yaml --batch-size 16（It's no use if weight is ' ' or yolov5m.pt/yolov5s.pt）

**Comment by emmobaby** [comment]
this is train_batch0.jpg, it seems my training is worked, however, pr is 0, too
![image](https://user-images.githubusercontent.com/32961372/197928652-a002709a-1873-42f7-a745-62f81b9035d2.png)

**Comment by HIT-Owen** [comment]
遇到了同样的问题，yolov5 yolov7模型训练过程中，P R mAP全是0，还有很多其他bug

**Comment by Malaxi** [comment]
Hello, have you solved this problem? I also encountered the problem of using different super parameter configuration files, some of which ran out numerical values, and some were 0

**Comment by Malaxi** [comment]
> this is train_batch0.jpg, it seems my training is worked, however, pr is 0, too ![image](https://user-images.githubusercontent.com/32961372/197928652-a002709a-1873-42f7-a745-62f81b9035d2.png)

Hello, have you solved this problem? I also encountered the problem of using different super parameter configuration files, some of which ran out numerical values, and some were 0

**Comment by Malaxi** [comment]
> this is train_batch0.jpg, it seems my training is worked, however, pr is 0, too ![image](https://user-images.githubusercontent.com/32961372/197928652-a002709a-1873-42f7-a745-62f81b9035d2.png)

Hello, have you solved this problem? I also encountered the problem of using different super parameter configuration files, some of which ran out numerical values, and some were 0
