### ISSUE TITLE
为什么用yolov5_hornet_tiny_s.yaml训练自己的数据集，跑出来的都是0

### ISSUE THREAD

**Issue by MrAccelerator** [iscyy/ultralyticsPro#132]
![图片](https://user-images.githubusercontent.com/56375036/198997178-0e9b2684-2418-42a4-a72b-7b210d7eb1e6.png)
请问这种问题应该如何呢？

**Comment by Malaxi** [comment]
我也遇到了这种情况，换了个超参数的配置就跑出来就是0

**Comment by Malaxi** [comment]
> ![图片](https://user-images.githubusercontent.com/56375036/198997178-0e9b2684-2418-42a4-a72b-7b210d7eb1e6.png) 请问这种问题应该如何呢？

请问楼主你解决了这个问题吗，我是用voc的超参数文件跑出来的就是0，但是使用其他超参数配置文件跑出来就有数字
