### ISSUE TITLE
can't train the model of YOLOX

### ISSUE THREAD

**Issue by Maokaicheng0725** [iscyy/ultralyticsPro#136]
When I train, the program will report errors：AttributeError: 'DetectX' object has no attribute 'anchors'

**Comment by jayphone17** [comment]
Try `from models.yolox import DetectX` ?

**Comment by iscyy** [comment]
#68

**Comment by Maokaicheng0725** [comment]
> #68

我试过这个方法，确实能训练但是第二个epoch的时候就报错了

**Comment by Maokaicheng0725** [comment]
> 

我试过了。。。还是不行。。。

**Comment by jayphone17** [comment]
> > 
> 
> 我试过了。。。还是不行。。。

我试了 --noautoanchor 是可以跑的

**Comment by jayphone17** [comment]
> > 
> 
> 我试过了。。。还是不行。。。

试一下再加一条 --otaloss yolox
