### ISSUE TITLE
训练YOLOv4，加载了权重报No module named 'mish_cuda'，未加载权重时报module 'torch.nn' has no attribute 'Mish'

### ISSUE THREAD

**Issue by jmlw8023** [iscyy/ultralyticsPro#137]
![image](https://user-images.githubusercontent.com/68936823/202853623-caeba150-8f16-4d2a-8bd0-5c22e283c764.png)

![image](https://user-images.githubusercontent.com/68936823/202853672-2521d0dd-edb8-41c2-8aab-2c9475eaa6f3.png)

**Comment by iscyy** [comment]
Install the corresponding mish_cuda
