### ISSUE TITLE
The verification result in the training is seriously inconsistent with the result of val.py

### ISSUE THREAD

**Issue by zmdcs** [iscyy/ultralyticsPro#138]
Hello, I encountered a very strange problem. At the end of the training, my mAP has reached 0.8, and then used best.pt for verification, but only 0.269. Why? More than one model has this problem.
![image](https://user-images.githubusercontent.com/40875421/203682315-0956d064-86b8-4888-9337-5d69a488d4cb.png)

**Comment by SusanJJN** [comment]
same question

**Comment by SusanJJN** [comment]
Try to adjust the '_imgsz_' to 160 instead of default 640. In the function _parse_opt()_ in _val.py_.
