### ISSUE TITLE
数据集的格式问题

### ISSUE THREAD

**Issue by Malaxi** [iscyy/ultralyticsPro#141]
作者你好，我想请问使用yolov7训练VOC数据集，请问生成的txt文件格式如下图所示正确吗？麻烦作者解答一下
![image](https://user-images.githubusercontent.com/73024098/204135413-802e10c4-6b26-4c83-9b8a-226b466a244d.png)

**Comment by iscyy** [comment]
It can be kept consistent with the official YOLOv5/v7

**Comment by iscyy** [comment]
It can be kept consistent with the official YOLOv5/v7
