### ISSUE TITLE
请问C3GC具体是什么主干网络呢？

### ISSUE THREAD

**Issue by zmdcs** [iscyy/ultralyticsPro#142]
yolov5-exp中的yaml文件中的C3GC这一类的主干网络，不知道作者具体是加的哪种主干网络，是不是只是在C3的基础上加了3层卷积网络？

**Comment by regainOWO** [comment]
@zmdcs C3GC应该是作者自己定义的，看源码中包含ContextBlock2d，ContextBlock2d包含ContextBlock, ContextBlock是convnext的一部分
