### ISSUE TITLE
compare with WongKinYiu/yolov7

### ISSUE THREAD

**Issue by wolfworld6** [iscyy/ultralyticsPro#144]
Thank you for your excellent work. I am so confused that used your project to train yolov7, as follows, the results seem to be abnormal. then I compared with the WongKinYiu's yolov7, it is normal，why?
the cols mean P，R，mAP@0.5
1.yours
![image](https://user-images.githubusercontent.com/18051979/206085004-e44739c9-2904-4f82-9cf5-980e0b417724.png)

2.WongKinYiu's
![image](https://user-images.githubusercontent.com/18051979/206085053-7c9c0c3f-e75e-4758-b9d9-eb8f56d027e5.png)

**Comment by akashAD98** [comment]
@wolfworld6 which yolov7 model have you tried? & have you tested best.pth ,I'm getting error at last epoch while saving model

**Comment by wolfworld6** [comment]
> @wolfworld6 which yolov7 model have you tried? & have you tested best.pth ,I'm getting error at last epoch while saving model

I tested on yolov7.yaml，the best.pth just like the up.
![image](https://user-images.githubusercontent.com/18051979/206446060-5dff97e5-e289-4013-b7cb-31ca740c4a73.png)

**Comment by akashAD98** [comment]
@wolfworld6  have you done inference testing on video ?

**Comment by iscyy** [comment]
use https://github.com/iscyy/yoloair2
