### ISSUE TITLE
为什么使用改进后的yolov7只要是加了swintransformer都会出现不匹配的问题怎么解决呢？

### ISSUE THREAD

**Issue by Ustinianxz** [iscyy/ultralyticsPro#146]
RuntimeError: shape '[32, 2, 8, 1, 8, 64]' is invalid for input of size 393216
![PGIU~ {Z~ F%T}MVF 4%9XT](https://user-images.githubusercontent.com/65543680/206609732-b5fa9948-76b2-41ee-8422-2e65232def6e.png)

**Comment by Seperendity** [comment]
同问，请问您知道问题在哪吗
