### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'float' WHEN TRAIN YOLOX MODEL

### ISSUE THREAD

**Issue by jayphone17** [iscyy/ultralyticsPro#149]
**BUG REPORT**

When I use following command to train YoloX Model

`python train.py --weights weights/yolox_s.pt --cfg configs/yolox/yolox-s.yaml --data data/MyCustomDataSet.yaml --device 1,2,3,4 --batch-size 64 --epoch 300
`

it appears BUG like: 
 
**Traceback (most recent call last):
  File "train.py", line 695, in <module>
    main(opt)
  File "train.py", line 591, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 128, in train
    csd = ckpt['model'].float().state_dict()  # checkpoint state_dict as FP32
AttributeError: 'collections.OrderedDict' object has no attribute 'float'**

I haved downloaded the weight **yolox_s.pt** from https://github.com/Megvii-BaseDetection/YOLOX to self-created folder "weights"

**Comment by iscyy** [comment]
You can use yolox-s.pt in [Assets](https://github.com/iscyy/yoloair/releases/tag/v1.0)
