### ISSUE TITLE
yoloair训练效果与yolov7原模型相差很大？

### ISSUE THREAD

**Issue by 3097254259** [iscyy/ultralyticsPro#152]
我自己的数据集，在yoloair中使用yolov7原模型效果（0.7%）远低于yolov7官方代码的效果（89%），参数设置一样的，请问这是怎么回事？

**Comment by iscyy** [comment]
use https://github.com/iscyy/yoloair2

**Comment by 3097254259** [comment]
作者你好，我用了您说的yoloair2了，效果还是不行，只有8%
