### ISSUE TITLE
不能找到ppyoloe++的详细模块

### ISSUE THREAD

**Issue by yutao007** [iscyy/ultralyticsPro#153]
感谢作者的yoloair项目，我看到您的readme中有ppyoloe++模块，想要借鉴一下。在configs中没有看到，只找到了PicoDet相关模块

**Comment by 3097254259** [comment]
of course it can be found.

**Comment by yutao007** [comment]
it can‘t be found  about ppyoloe++. just  can  be found  about  PicoDet .

**Comment by 3097254259** [comment]
噢噢，那就不知道捏
