### ISSUE TITLE
model training started but inside model summary its showing false

### ISSUE THREAD

**Issue by akashAD98** [iscyy/ultralyticsPro#157]
What's wrong with this, i was able to complete my epoch training, but in summary, its showing this  False, I tried configs/yolov7improved/yolov7-VoVGSCSP.yaml  , its really using vovGscsp, or its normal training?  what should I need to do to make it True? @iscyy @WangQvQ 

configs/yolov7improved/yolov7-VoVGSCSP

<img width="662" alt="image" src="https://user-images.githubusercontent.com/62583018/210819388-94f42250-0f26-464a-a3d4-20d0a5eb1e4e.png">

**Comment by chihuajiao** [comment]
Can you show your error message? i don't quite understand what you mean

**Comment by akashAD98** [comment]
its correct,its showing False here, so I'm confused about whether this neck part model is using @chihuajiao 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/62583018/210972118-d025d075-6e00-4b41-8e01-6ff905a0a865.png">

**Comment by chihuajiao** [comment]
Sorry, I can't solve your problem. Because I am a novice. I think you can try to change it to True or use VScode to view the source code

**Comment by akashAD98** [comment]
I saw the code there is no any option to make it True

**Comment by WangQvQ** [comment]
It's easy, you just need change yolov7-VoVGSCSP.yaml ，
![image](https://user-images.githubusercontent.com/58406737/211003345-2cfc71b5-9f0f-4b28-ba9a-5fc0d45200ed.png)
![image](https://user-images.githubusercontent.com/58406737/211003401-ca0052a0-66e6-40c0-8eed-66a495af689f.png)

**Comment by akashAD98** [comment]
@WangQvQ where should i change,in .yaml ,which line can you please tell me

**Comment by WangQvQ** [comment]
@akashAD98 
![image](https://user-images.githubusercontent.com/58406737/211007298-ec139066-b8d7-4e5e-aa80-b1046e72dc3d.png)

**Comment by akashAD98** [comment]
Ohh its inside .yaml 😅,thanks I haven’t  checked it,I thought it’s insode common.py or code
