### ISSUE TITLE
about yolov7

### ISSUE THREAD

**Issue by SHU-er** [iscyy/ultralyticsPro#22]
thank you for your working, I have some question hope you can tell me: 

change the --cfg to yolov7, by training, I get the weight best.pt 
but when val, it cause a error 
........torch.nn.modules.module.ModuleAttributeError: 'IDetect' object has no attribute 'end2end'.....

**Comment by iscyy** [comment]
hi, thanks, You should update the latest code

**Comment by SHU-er** [comment]
thank you for you remand，I have get the changeing about yolov7

but, when I try to change the --cfg to yolox-m.yaml，It even can not strat to train......
did you have meet this question? or some thing else I have not get ? hope you can tell me, thanks

by input this------" python train.py --cfg E:\00_reWriteCode\yoloair-main\configs\yolox\yolox-m.yaml "
I get error:
**********************************************************************
..........................
module 'signal' has no attribute 'SIGALRM'
Traceback (most recent call last):
  File "train.py", line 690, in <module>
    main(opt)
  File "train.py", line 586, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 253, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "E:\00_reWriteCode\yoloair-main\utils\autoanchor.py", line 43, in check_anchors
    anchors = m.anchors.clone() * m.stride.to(m.anchors.device).view(-1, 1, 1)  # current anchors
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'DetectX' object has no attribute 'anchors'
************************************************************************************************************************

**Comment by iscyy** [comment]
add `--noautoanchor`

**Comment by SHU-er** [comment]
thank you very much, I have got it !
