### ISSUE TITLE
MobileOne如何导出重参化模型?

### ISSUE THREAD

**Issue by ChungTak** [iscyy/ultralyticsPro#24]
看你的[MobileOne文章](https://blog.csdn.net/qq_38668236/article/details/126157859) 描述训练和推理模型不一样~~
使用 configs/yolov5-Improved/yolov5s_mobileone_backbone.yaml 训练出来的是training模型吗？ 如何转化为推理模型?

**Comment by iscyy** [comment]
The inference code for the Mobileone part has been tested and will be updated soon

**Comment by HiiHongFe** [comment]
请问更新了吗
