### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by 17076372880** [iscyy/ultralyticsPro#27]
使用yolov5进行训练，train的时候没有问题，训练完一个epoch之后，进行验证的时候会报错误：RuntimeError: expected scalar type Half but found Float，请问是哪里出的问题？使用的v100显卡

**Comment by iscyy** [comment]
Which configuration to train?

**Comment by 827346462** [comment]
> Which configuration to train?
i train /transformer/yolov5s_swinv2_head.yaml met this pro
![image](https://user-images.githubusercontent.com/50097546/201506416-799e20c0-94ef-45a7-9e8a-307a1cd54a08.png)
