### ISSUE TITLE
QueryDet

### ISSUE THREAD

**Issue by coderonion** [iscyy/ultralyticsPro#28]
Are you considering implementing QueryDet(CVPR 2022) network with yolov5 style? I think it's great!
https://github.com/ChenhongyiYang/QueryDet-PyTorch

**Comment by WangQvQ** [comment]
这个有点难度吧

**Comment by iscyy** [comment]
This paper looks great, I didn't read it carefully, but it doesn't seem to be very popular

**Comment by iscyy** [comment]
This paper looks great, I didn't read it carefully, but it doesn't seem like it's very popular
