### ISSUE TITLE
KeyError: 'ema'

### ISSUE THREAD

**Issue by kay2019-art** [iscyy/ultralyticsPro#44]
Traceback (most recent call last):
  File "detect.py", line 257, in <module>
    main(opt)
  File "detect.py", line 252, in main
    run(**vars(opt))
KeyError: 'ema'

**Comment by iscyy** [comment]
If this is a custom training Question, please provide as much information as possible.
If this is a Bug Report, please provide screenshots and minimum viable code to reproduce your issue, otherwise we can not help you.

**Comment by Yshelgi** [comment]
try to use this code,because load yolov7.pt the 'ema' not in keys
`ckpt = (ckpt.get('ema') or ckpt['model']).float()`
![image.png](https://s2.loli.net/2022/09/10/arzkwnWj7CDelZK.png)
