### ISSUE TITLE
训练YOLOX-S

### ISSUE THREAD

**Issue by vaerdu** [iscyy/ultralyticsPro#45]
用自己的数据集训练本仓库的YOLOX-S比官方YOLOX-S要高6-7个点，本仓库YOLOX代码和官方YOLOX代码哪里不一样吗？

**Comment by iscyy** [comment]
Compared with the official, there are some optimizations, and the training method adopts the parameter configuration of yolov5

**Comment by vaerdu** [comment]
> Compared with the official, there are some optimizations, and the training method adopts the parameter configuration of yolov5

对比了下，本仓库的YOLOX-S参数量约为8.0M，官方YOLOX-S参数量是8.9M，请问是改变了什么模块吗？只是超参数的调整不应该参数量不一致吧

**Comment by lunaWU628** [comment]
> 用自己的数据集训练本仓库的YOLOX-S比官方YOLOX-S要高6-7个点，本仓库YOLOX代码和官方YOLOX代码哪里不一样吗？

你好，请问你是怎么训练的yolox呢？这个存储库不是yolov5的嘛

**Comment by vaerdu** [comment]
> > 用自己的数据集训练本仓库的YOLOX-S比官方YOLOX-S要高6-7个点，本仓库YOLOX代码和官方YOLOX代码哪里不一样吗？
> 
> 你好，请问你是怎么训练的yolox呢？这个存储库不是yolov5的嘛
仓库里，configs文件夹里有yolox的网络结构

**Comment by lunaWU628** [comment]
嗯嗯，看到了，所以我想用这个存储库的yolox进行训练的话，把这个命令：
`python path/to/train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640`
改成：
`python path/to/train.py --data coco128.yaml --weights '' --cfg yolox.yaml --img 640` 就可以了嘛

**Comment by vaerdu** [comment]
> 嗯嗯，看到了，所以我想用这个存储库的yolox进行训练的话，把这个命令： `python path/to/train.py --data coco128.yaml --weights '' --cfg yolov5s.yaml --img 640` 改成： `python path/to/train.py --data coco128.yaml --weights '' --cfg yolox.yaml --img 640` 就可以了嘛

中间可能会报一些错误，根据错误修改就跑通了，在issue可以查找解决办法

**Comment by lunaWU628** [comment]
好的，感谢~

**Comment by JianghaiHe777** [comment]
请问，在训练yolox的时候，训练到一定epoch时，发生报错：

assertion input_val zero && input_val one cuda trigger
RuntimeError: CUDA error: device-side assert triggered

怎么解决呢？
感谢大佬们解答！
