### ISSUE TITLE
This happens when I train my dataset with yolox：ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#53]
Epoch   gpu_mem       box       obj       cls    labels  img_size
      0/99     1.95G     4.366     8.054     1.459       149       640: 100%|██████████| 14/14 [01:18<00:00,  5.64s/it]                                                                
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/1 [00:02<?, ?it/s]                                                          
Traceback (most recent call last):
  File "train.py", line 695, in <module>
    main(opt)
  File "train.py", line 591, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 416, in train
    results, maps, _ = val.run(data_dict,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/yoloair/val.py", line 196, in run
    out, train_out = model(im) if training else model(im, augment=augment, val=True)  # inference, loss outputs
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by iscyy** [comment]
add `--otaloss yolox`
