### ISSUE TITLE
Training a dataset from voc to yolo format gives a ValueError: not enough values to unpack (expected 2, got 1).

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#55]
Training a dataset from voc to yolo format gives a ValueError: not enough values to unpack (expected 2, got 1).
![image](https://user-images.githubusercontent.com/105439021/189082108-6e5d8598-2ee5-4d9f-91ef-0a7f93e0d573.png)

**Comment by iscyy** [comment]
add `--otaloss yolox`
