### ISSUE TITLE
Running val.py brings up ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#58]
Running val.py brings up ValueError: not enough values to unpack (expected 2, got 1)
![image](https://user-images.githubusercontent.com/105439021/189359731-b582e6ec-19cf-4add-ae23-171ab6fd0ee0.png)
val.py No   parser.add_argument('--otaloss', type=str, default='origin', help='use yolov7 or yolox')
How can I solve it?

**Comment by iscyy** [comment]
You can update the latest code, or update val.py, add ` --otaloss yolox` when running val.py

**Comment by ghost** [comment]
> You can update the latest code, or update val.py, add ` --otaloss yolox` when running val.py
Thank you, solved
