### ISSUE TITLE
The fusevggforward() is missing

### ISSUE THREAD

**Issue by Yshelgi** [iscyy/ultralyticsPro#62]
while using yolov5-lite model to val,m.fusevggforward() is missing In /models/Models/Litemodel.py,RepVGGBlock class
Please add missing code
``` python
    def fusevggforward(self, x):
        return self.nonlinearity(self.rbr_dense(x))

**Comment by iscyy** [comment]
Regarding the part of the RepVGG model, the `fusevggforward function` has been deleted, because some of the updates in yolo.py are not yet in the main branch, and will be updated in the main branch later, adding `switch_to_deploy`

**Comment by Yshelgi** [comment]
> 关于RepVGG模型的部分，`fusevggforward function`已经删掉了，因为yolo.py中的一些更新还没有到主分支，后面会在主分支更新，补充`switch_to_deploy`

yeah,using m.switch_to_deploy() also works
