### ISSUE TITLE
assert 'nc' in data, "Dataset 'nc' key missing."

### ISSUE THREAD

**Issue by jia0511** [iscyy/ultralyticsPro#63]
遇到这个问题是怎么回事的？

**Comment by yang-0201** [comment]
有没有可能是你的数据集的标注有问题，检查一下

**Comment by jia0511** [comment]
我用yolov5官方框架训练没问题，用yoloair训练yolov5就出了问题

**Comment by iscyy** [comment]
If this is a custom training Question, please provide as much information as possible.
If this is a Bug Report, please provide screenshots and minimum viable code to reproduce your issue, otherwise we can not help you.

**Comment by Bob-jpg** [comment]
查看你的utils/general.py下的代码354后加上 data['nc'] = len(data['names']) 即可

**Comment by HutaoAI** [comment]
这个问题我也遇到了 要如何解决
