### ISSUE TITLE
RuntimeError: shape '[32, 4, 1600]' is invalid for input of size 51200

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#65]
![image](https://user-images.githubusercontent.com/105439021/189517505-106087cb-1c2f-43f7-8eff-eb9658b68054.png)
Replace YOLOx-s backbone with MobileNetV3-small,the above-mentioned problems have occurred,I configured it according to yolov5-mobile3s.yaml,
How do I solve it?

**Comment by ghost** [comment]
Resolved!

**Comment by WenHui001** [comment]
How did you resolve it?
