### ISSUE TITLE
NameError: name 'SwinV2_CSPB' is not defined

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#66]
Error running yolov5s-swintransformer_v2.yaml.
![image](https://user-images.githubusercontent.com/105439021/189517842-20de6b10-70e3-4e3a-b113-07bdd1b55003.png)

**Comment by ghost** [comment]
I cloned the latest one and it didn't work

**Comment by iscyy** [comment]
You can use the `yolov5s-swintransformer_v2.yaml` file with the latest code,
