### ISSUE TITLE
I used YOLOv7 to train my dataset, after dozens of epochs the mAP did not go up, it was always around 0.00005, I did not change the parameters, but I used the code on the YOLOv7 side, the mAP was able to go up normally, why is this?

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#70]
I used YOLOv7 to train my dataset, after dozens of epochs the mAP did not go up, it was always around 0.00005, I did not change the parameters, but I used the code on the YOLOv7 side, the mAP was able to go up normally, why is this?
![image](https://user-images.githubusercontent.com/105439021/189564179-8745ecf1-4b53-4771-af51-2bcb0e115f7f.png)
This is the result of running the code using yolov7's side

**Comment by iscyy** [comment]
Switch the branch from main to the yolov7-air branch, you can use the code of the yolov7-air branch for yolov7 training

**Comment by ghost** [comment]
> Switch the branch from main to the yolov7-air branch, you can use the code of the yolov7-air branch for yolov7 training

Do you mean I don't use the YOLOv7 code in yoloair for training? --cfg with yolov7's side of the config file?

**Comment by iscyy** [comment]
The same is the yoloair repo, the default branch is Main, this is another branch, (yolov7-air): https://github.com/iscyy/yoloair/tree/yolov7-air , you can use this branch for training first . Will be merged into Main branch later

**Comment by ghost** [comment]
Thank you！！
