### ISSUE TITLE
请问关于一些非yolo官方的模型权重参数如何获取

### ISSUE THREAD

**Issue by Cxgmg** [iscyy/ultralyticsPro#72]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

例如飞桨的PicoDet可以在yoloair中复现成功，但是飞桨官方的权重文件是.pdparams格式，训练这类模型有办法可以使用到他们的官方权重参数吗。

**Comment by iscyy** [comment]
There are some differences between PicoDet and the original PicoDet model. For this pre-training weight, maybe you can use the COCO dataset for training first.
