### ISSUE TITLE
能支持更高效的数据加载方式吗？

### ISSUE THREAD

**Issue by trouble-maker007** [iscyy/ultralyticsPro#73]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar feature requests.

### Description

我想使用coco数据重新训练一下，发现数据加载到训练的时间特别长，如果使用lmdb会高效一点吗

### Use case

减少训练时间

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by iscyy** [comment]
The data loading method of this repo is stable and applicable. It is based on yolov5. If you need to change, you can customize anything you want, but it will naturally take some effort.
