### ISSUE TITLE
训练yolox，输出的结果图中没有val损失曲线

### ISSUE THREAD

**Issue by vaerdu** [iscyy/ultralyticsPro#75]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/78519509/189919124-b47e373d-50da-4209-8777-61ba12f9cff4.png)

**Comment by wenjunx** [comment]
有大佬说一下为什么吗

**Comment by iscyy** [comment]
Yes, no loss calculation is performed during val
