### ISSUE TITLE
Is there any idea to integrate the RES2NET structure

### ISSUE THREAD

**Issue by songjiahao-wq** [iscyy/ultralyticsPro#76]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Is there any idea to integrate the RES2NET structure

**Comment by iscyy** [comment]
This is a good suggestion, if there is time, it can be integrated,
at the same time, We encourage you to submit a Pull Request (PR) to help improve YOLOAir for everyone

**Comment by iscyy** [comment]
The res2net backbone update has been completed, https://github.com/iscyy/yoloair/blob/main/configs/backbone/yolov5_res2net50.yaml

**Comment by songjiahao-wq** [comment]
> res2net主干更新已经完成，https://github.com/iscyy/yoloair/blob/main/configs/backbone/yolov5_res2net50.yaml
Thank you very much

**Comment by songjiahao-wq** [comment]
> res2net主干更新已经完成，https://github.com/iscyy/yoloair/blob/main/configs/backbone/yolov5_res2net50.yaml

您是否有兴趣添加BoTNet呢，就像C3TR模块一样

**Comment by iscyy** [comment]
updated a long time ago
