### ISSUE TITLE
I trained with the recently updated yolov7 code and got an Exception: Dataset not found.

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#78]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar feature requests.

### Description

![image](https://user-images.githubusercontent.com/105439021/190152745-68b7adae-4fb9-45e8-b91d-695b2cd0d0f3.png)
This is a mistake！！
![image](https://user-images.githubusercontent.com/105439021/190153093-8778327b-f047-43ce-a8f9-19fafcaede33.png)

Here are my instructions.

**Comment by iscyy** [comment]
Adjust dataset path
