### ISSUE TITLE
I'd like to see what kind of ComputeLoss yolov7 uses? It's not mentioned in the config file.

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#79]
I'd like to see what kind of ComputeLoss yolov7 uses? It's not mentioned in the config file.

**Comment by Luxiangxianghy** [comment]
You can select otaloss in train.py under main, but you can't see it in train.py under yolov7.

**Comment by iscyy** [comment]
To train the yolov7 model, you can directly use the code in the yolov7 directory
