### ISSUE TITLE
 Can I ask if the upgrade of yolov7 is based on that version of yolov7?

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#82]
![image](https://user-images.githubusercontent.com/105439021/190444682-73d7a313-b1de-4f1b-84ab-841d70ee2710.png)
Which version of YOLOv7 are these changes based on?

**Comment by iscyy** [comment]
official yolov7.yaml

**Comment by ghost** [comment]
> official yolov7.yaml

ok!!Thank you!!
