### ISSUE TITLE
This is no way to train yolov7

### ISSUE THREAD

**Issue by ghost** [iscyy/ultralyticsPro#83]
![image](https://user-images.githubusercontent.com/105439021/190539329-5c40c466-db67-42be-a947-9fe2ec5f723e.png)
NameError: name 'CNeB' is not defined
use  yolov7/train.py --cfg configs/yolov7-transformer-Improved/   ， not work

**Comment by iscyy** [comment]
Which branch of yoloair are you using now? You need to add the `CNeB` module

**Comment by ghost** [comment]
> Which branch of yoloair are you using now? You need to add the `CNeB` module

main,the common.py under yolov7/train doesn't have,I tried to add it, but there was an error.

**Comment by iscyy** [comment]
You can try adding it yourself, or wait for the code to be updated later

**Comment by ghost** [comment]
> You can try adding it yourself, or wait for the code to be updated later

ok，thanks！！
