### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 233: illegal multibyte sequence

### ISSUE THREAD

**Issue by nooicess** [iscyy/ultralyticsPro#85]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar bug report.

### YOLOAir Component

Training

### Bug

![VA3A_H{Q%2E4PT@ 124UTRD](https://user-images.githubusercontent.com/105474091/190627418-d0031f3d-a1f5-4b9d-80af-3a6843d5fd26.png)

### Additional

使用的yolov7里面的train，外面的train没有这个问题

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by iscyy** [comment]
What training command was used?

**Comment by nooicess** [comment]
> What training command was used?
解决了，使用的yolov7/train.py。66行加个encoding='utf-8'    可以了
with open(opt.data,encoding='utf-8') as f:                      
        data_dict = yaml.load(f, Loader=yaml.SafeLoader)  # data dict

**Comment by zhongsir771** [comment]
帮大忙啦，兄弟，thanks！
