### ISSUE TITLE
How to use graph neural network in yoloair？

### ISSUE THREAD

**Issue by 985zhangguoxu** [iscyy/ultralyticsPro#86]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Dear author

     Thank you for writing the yoloair project. I see the application of project support graph neural network in yolo. I don't know anything about graph neural networks. Which file is the combination of graph neural network and YOLO? How to use it?

**Comment by iscyy** [comment]
Subsequent updates in Main
