### ISSUE TITLE
AssertionError: weights/mobilenet_v3_small-047dcff4.pth acceptable suffix is ['.pt']

### ISSUE THREAD

**Issue by maoguotao-jr10** [iscyy/ultralyticsPro#89]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

我在训练yolov5s-mobilenet时，会自动在网上下载mobilenet_v3_small-047dcff4.pth的权重，但有以下报错
Traceback (most recent call last):
  File "D:\yoloair-main\train.py", line 693, in <module>
    main(opt)
  File "D:\yoloair-main\train.py", line 589, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\yoloair-main\train.py", line 118, in train
    check_suffix(weights, '.pt')  # check weights
  File "D:\yoloair-main\utils\general.py", line 354, in check_suffix
    assert s in suffix, f"{msg}{f} acceptable suffix is {suffix}"
AssertionError: weights/mobilenet_v3_small-047dcff4.pth acceptable suffix is ['.pt']

**Comment by iscyy** [comment]
Use this repository to test the model training, it can run normally without this error
Are you training in the default environment or custom modified?

**Comment by maoguotao-jr10** [comment]
I encountered the error while training, using the default environment

**Comment by maoguotao-jr10** [comment]
Whether the current repository does not support pre-trained models with the suffix ".pth"
