### ISSUE TITLE
关于改进的效果比对疑问

### ISSUE THREAD

**Issue by WangRongsheng** [iscyy/ultralyticsPro#90]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

你好，请问对于改进的idea有没有建立已经试验过的精确度比对表，或者那些加在个人数据集中大概率能获得提升的idea？

**Comment by iscyy** [comment]
1.there are too many modules, training COCO requires a lot of GPU resources. Most of the modules have been trained, and some modules can **work**. 
2.The training experimental data will not be released for the time being. Different data sets perform differently, you can do experiments yourself.

**Comment by WangRongsheng** [comment]
thank you！
