### ISSUE TITLE
about SEAttention issues

### ISSUE THREAD

**Issue by konioy** [iscyy/ultralyticsPro#91]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Why only the last output of head has SE? Is this the best location you've ever experimented with?

**Comment by yang-0201** [comment]
Adding this SE attention layer to the file is just an example, you can add this attention to as many layers as you want, but in the meantime, some numerical parameters in the file need to be adjusted accordingly. Adding attention may not always work for different data sets, and you will need to experiment with where to add it.

**Comment by konioy** [comment]
ok,thanks
