### ISSUE TITLE
训练过程中出现NotImplementedError: There were no tensor arguments to this function

### ISSUE THREAD

**Issue by lixiangMindSpore** [iscyy/ultralyticsPro#94]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

训练过程中出现NotImplementedError: There were no tensor arguments to this function，如下图所示
![b3615fbb7ed073cab8c6ebf21c5004b](https://user-images.githubusercontent.com/78945582/191158224-8e4ae06c-3a76-46fa-9716-09bf64465ca8.jpg)

**Comment by iscyy** [comment]
What is the training command

**Comment by iscyy** [comment]
What training command are you using?

**Comment by lixiangMindSpore** [comment]
> What training command are you using?

python train.py --data coco.yaml --weight '' --cfg configs/yolox-Improved/yolox-convnext_s_backbone.yaml --img 640  --noautoanchor

**Comment by iscyy** [comment]
> > 你使用什么训练命令？
> 
> python train.py --data coco.yaml --weight '' --cfg configs/yolox-Improved/yolox-convnext_s_backbone.yaml --img 640 --noautoanchor

Just used this training command to test, it works fine, can't reproduce this error,

**Comment by lixiangMindSpore** [comment]
> > > 你使用什么训练命令？
> > 
> > 
> > python train.py --data coco.yaml --weight '' --cfg configs/yolox-Improved/yolox-convnext_s_backbone.yaml --img 640 --noautoanchor
> 
> Just used this training command to test, it works fine, can't reproduce this error,

python train.py --data coco.yaml --weight '' --cfg configs/yolox-Improved/yolox-convnext_s_backbone.yaml --img 640  --noautoanchor  --otaloss yolox
Maybe this comand is right.

**Comment by iscyy** [comment]
Yes, the otaloss parameter needs to be added to the val stage, which will affect the val, but your screenshot has not yet reached this step, and you are still running the train of the first epoch

**Comment by lixiangMindSpore** [comment]
> Yes, the otaloss parameter needs to be added to the val stage, which will affect the val, but your screenshot has not yet reached this step, and you are still running the train of the first epoch

I add otaloss parameter, the error can be dispeared.
