### ISSUE TITLE
it's too slow that use GPU

### ISSUE THREAD

**Issue by Alioth5670** [iscyy/ultralyticsPro#96]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

When I train YOLOv5 model with yoloair, it's slower than the model in official yolov5, and Volatile GPU-Util less than 10% in my windows PC, with NVIDIA GeForce 2080Ti.

### Additional

use command:
`python train.py  --weights ' ' --cfg configs/yolov5-standard/yolov5s.yaml --img 640  --bitch-size 16`

**Comment by yang-0201** [comment]
maybe you shoud set "--wokers" to 8

**Comment by Alioth5670** [comment]
` parser.add_argument('--workers', type=int, default=8, help='max dataloader workers (per RANK in DDP mode)')`
In train.py, it is default that workers are set to 8. ​So does it have another way to deal with this case?

**Comment by yang-0201** [comment]
try to set "--device" to 0

**Comment by Alioth5670** [comment]
​I have done the same thing before, but this method didn't work.

**Comment by iscyy** [comment]
The training of yolov5 is consistent with the official one, and the situation you said will not occur. Can you post your train.py parameter part?

**Comment by Alioth5670** [comment]
OMG！ I confused the 'train.py' of official YOLOv5 and YOLOAIR, which were opened in the same windows. In the official version, 'workers' was set to 8, but not in yoloair. I'm sorry to trouble you. Thank you for your patience.
