### ISSUE TITLE
Have you tested all the models? Is there a table of evaluation indicators, such as MAP

### ISSUE THREAD

**Issue by tianjun-world** [iscyy/ultralyticsPro#98]
### Search before asking

- [X] I have searched the YOLOAir [issues](https://github.com/iscyy/yoloair/issues) and found no similar questions.

### Question

Hello author, thank you very much for providing such an excellent code base. Have you tested all the models? Is there a table of evaluation indicators, such as MAP, etc. I would like to know the mAP of yolov7 DecoupHeadX

**Comment by iscyy** [comment]
tested all models,
Regarding the combination of yolov7-DetectX, you can try the experiment on your own dataset
